name = "franzai-bridge-v2"
compatibility_date = "2025-12-31"
account_id = "ecf21e85812dfa5b2a35245257fc71f5"

[site]
bucket = "./public"

[[routes]]
pattern = "bridge.franzai.com"
custom_domain = true
